---
title: "Lab 9: Generative Art"
author: "Allen Choi"
format:
  html:
    code-fold: show
    code-summary: "Click to hide/show the code"
    code-overflow: wrap
    toc: true
embed-resources: true
editor: source
---

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(tibble)
library(scales)
library(ggthemes)
library(rayshader)
library(ambient)
library(tictoc)
```

# Penguins
```{r}
penguins
```

# Disease
```{r}
## The code is from https://art-from-code.netlify.app/day-1/session-4/
sample_canva2 <- function(seed = NULL, n = 4) {
  
  if(!is.null(seed)) set.seed(seed)
  sample(ggthemes::canva_palettes, 1)[[1]] |>
    (\(x) colorRampPalette(x)(n))()  
}

transform_to_curl_space <- function(x, y, frequency = 5, octaves = 10) {
  curl_noise(
    generator = fracture,
    noise = gen_simplex,
    fractal = fbm,
    octaves = octaves,
    frequency = frequency,
    x = x,
    y = y
  )
}


define_worley_cells <- function(x, y, frequency = 2, octaves = 6) {
  fracture(
    noise = gen_worley,
    fractal = billow,
    octaves = octaves,
    frequency = frequency,
    value = "cell",
    x = x,
    y = y
  ) |>
    rank() |> 
    normalise()
}

simplex_noise <- function(x, y, frequency = .1, octaves = 10) {
  fracture(
    noise = gen_simplex,
    fractal = ridged,
    octaves = octaves,
    frequency = frequency,
    x = x,
    y = y
  ) |>
    normalise()
}

ice_floe <- function(seed) {

  set.seed(seed)
  
  grid <- long_grid(
    x = seq(0, 1, length.out = 2000),
    y = seq(0, 1, length.out = 2000)
  )
  
  coords <- transform_to_curl_space(grid$x, grid$y)
  
  grid |>
    mutate(
      cells = define_worley_cells(coords$x, coords$y),
      paint = simplex_noise(x + cells, y + cells),
      paint = normalise(paint)
    ) |>
    as.array(value = paint)
}


shaded_ice_floe <- function(seed) {
  
  art <- ice_floe(seed)
  
  height_shade(
    heightmap = art,
    texture = sample_canva2(seed, 50)
  ) |>
    add_shadow(
      shadowmap = ray_shade(
        heightmap = art, 
        sunaltitude = 45, 
        sunangle = 135,
        multicore = TRUE, 
        zscale = .005
      ), 
      max_darken = 0.01
    ) |>
    plot_map()
}

shaded_ice_floe(12345)
```
Changed the frequency and octaves which changed the size of the "cell walls"
Sun Angle I chose as 135 for the light to come from the bottom right
Sun altitude maybe 40 for the light to come at an angle